@startuml

class LineTranslation {
    +name
    +font
    +fontsize
    +scale_x
}

class StationTranslation extends LineTranslation {
    +enter_xy
    +exit_xy
}

class TerminusTranslation extends StationTranslation {
    +terminus
    +name_after_terminus
    +xy
    +combined_enter_xy
    +combined_exit_xy
}

class Transition {
    +names: list[StationTranslation]
    +xy: list[int]
    +from_json()
}

class TerminusTransition extends Transition {
    +names: list[TerminusTranslation]
    +terminus_number: str
}

class StationTransition {
    +names : list[StationTranslation]
    +xy: list[int]
    +station_number: str
    +transfers: list[list[LineTranslation]]
    +skip: bool
    +from_json_list()
}

Transition *-up-> "StationTranslation": 0..*
StationTransition *-up-> "StationTranslation": 0..*
StationTransition *-up--> LineTranslation: 0..*

TerminusTransition *-up-> "TerminusTranslation": 0..*

@enduml
