@startuml

class LineTranslation {
    +name
    +font
    +fontsize
    +scale_x
}

class StationTranslation extends LineTranslation {
    +enter_xy
    +exit_xy
}

class TerminusTranslation extends StationTranslation {
    +terminus
    +name_after_terminus
    +xy
    +combined_enter_xy
    +combined_exit_xy
}

class CircularList<T> {
    +it: list[T]
    +head: int
    +curr()
    +iter()
    +pairs()
}

class Transition {
    +names: CircularList[StationTranslation]
    +xy: list[int]
    +from_json()
}

class TerminusTransition extends Transition {
    +names: CircularList[TerminusTranslation]
    +terminus_number: str
}

class StationTransition {
    +names : CircularList[StationTranslation]
    +xy: list[int]
    +station_number: str
    +transfers: list[list[LineTranslation]]
    +skip: bool
    +from_json_list()
}


"CircularList[StationTranslation]" --up-> CircularList: T -> StationTranslation
"CircularList[StationTranslation]" *-up-> StationTranslation
"CircularList[TerminusTranslation]" --up-> CircularList: T -> TerminusTranslation
"CircularList[TerminusTranslation]" *-up-> TerminusTranslation

Transition *-up-> "CircularList[StationTranslation]"
StationTransition *-up-> "CircularList[StationTranslation]"
StationTransition *-up--> LineTranslation

TerminusTransition *-up-> "CircularList[TerminusTranslation]"

@enduml
