@startuml
@startjson

{
    "states": {
        "next": {
            "translations": [
                {
                    "name": "つぎは",
                    "font": "Hiragino Sans GB W3",
                    "fontsize": 70,
                    "enter_xy": [960,250],
                    "exit_xy": [960,330],
                    "scale_x": 1
                },
                {
                    "name": "Next",
                    "font": "Roboto",
                    "fontsize": 60,
                    "enter_xy": [960,250],
                    "exit_xy": [960,330],
                    "scale_x": 1
                }
            ],
            "xy": [300,280]
        }
    }
}

@endjson
@enduml
