@startuml
@startjson

{
    "terminal": {
        "translations": [
            {
                "name": "ゆき",
                "terminus": "西武新宿",
                "font": "Hiragino Sans GB W3",
                "fontsize": 70,
                "combined_enter_xy": [1500,35],
                "combined_exit_xy": [1500,100],
                "enter_xy": [1500,35],
                "exit_xy": [1500,100],
                "scale_x": 1,
                "name_after_terminus": true,
                "xy": [650,70]
            },
            {
                "name": "For",
                "terminus": "Seibu Shinjuku",
                "font": "Roboto",
                "fontsize": 60,
                "combined_enter_xy": [700,35],
                "combined_exit_xy": [700,110],
                "enter_xy": [700,35],
                "exit_xy": [700,110],
                "scale_x": 0.8,
                "name_after_terminus": false,
                "xy": [650,70]
            }
        ],
        "xy": [650,70],
        "terminus_number": "SS-01"
    }
}

@endjson
@enduml
